version: "3.2"
services:
  web:
    build:
      context: ../
      dockerfile: docker/development/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ../
        target: /app
  db:
    environment:
      POSTGRES_DB: tt
      POSTGRES_USER: tt
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
volumes:
  dbdata:
