# Generated by Django 2.1 on 2018-08-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendGridEmail',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='title')),
                ('template_id', models.CharField(max_length=64, verbose_name='template ID')),
            ],
            options={
                'verbose_name': 'SendGrid email',
                'verbose_name_plural': 'SendGrid emails',
                'ordering': ['title'],
            },
        ),
    ]
