# Generated by Django 2.1 on 2018-08-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("apps_emails", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="sendgridemail",
            name="categories",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="categories"
            ),
        )
    ]
