# Generated by Django 2.2.4 on 2019-09-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("apps_emails", "0002_sendgridemail_categories")]

    operations = [migrations.DeleteModel(name="SendGridEmail")]
