language: python

python:
  - 3.6

services:
  - docker

before_install:
  - sudo service postgresql stop

  # Install Terraform.
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
  - unzip /tmp/terraform.zip -d ~/bin
  - rm -f /tmp/terraform.zip

  - cp .env.example .env

install:
  - sh scripts/docker-compose.sh build

script:
  - sh scripts/format.sh --check
  - sh scripts/test.sh

after_success:
  - sudo mkdir /app
  - sudo cp -r project /app/project
  - pip install coveralls
  - coveralls

after_script:
  - sh scripts/docker-compose.sh down -v

deploy:
  provider: script
  script: sh scripts/deploy.sh
  on:
    tags: true
