dist: xenial

language: python

python: 3.8

services:
  - docker

stages:
  - name: check
    if: |
      tag IS blank && \
      branch != qa

  - name: deploy
    if: |
      tag IS present || \
      branch = qa

jobs:
  include:
    - stage: check
      name: lint
      before_install: skip
      install: docker-compose build
      script: scripts/lint

    - stage: check
      name: test
      before_install:
        - sudo service postgresql stop
        - cp .env.example .env
      install: docker-compose build
      # FIXME: running as root user to avoid permission issues with coverage.
      script: scripts/run --user root web sh scripts/_test
      after_success:
        - sudo mkdir /app
        - sudo cp -r project /app/project
        - pip install coveralls
        - coveralls

    - stage: deploy
      name: qa
      if: branch = qa
      before_install: skip
      install: skip
      script: skip
      after_success: true
      deploy:
        provider: script
        script: scripts/deploy qa
        on:
          branch: qa

    - stage: deploy
      name: production
      if: tag IS present
      before_install: skip
      install: skip
      script: skip
      after_success: true
      deploy:
        provider: script
        script: scripts/deploy production
        on:
          tags: true

notifications:
  email:
    on_success: never
