language: python

python:
  - 3.6

services:
  - docker

before_install:
  - sudo service postgresql stop
  - cp .env.example .env

install:
  - sh scripts/docker-compose.sh build

script:
  - sh scripts/format.sh --check
  - sh scripts/test.sh

after_success:
  - sudo mkdir /app
  - sudo cp -r project /app/project
  - pip install coveralls
  - coveralls

after_script:
  - sh scripts/docker-compose.sh down -v
