language: python

python:
  - 3.6

services:
  - docker

install:
  - docker-compose build

before_script:
  - sudo service postgresql stop
  - cp .env.example .env

script:
  - sh scripts/lint.sh
  - sh scripts/test.sh
