dist: xenial
language: python
python: 3.7

services:
  - docker

jobs:
  include:
    - stage: lint_and_test
      name: "Lint and Test"
      if: tag IS blank && branch != qa
      before_install:
        - sudo service postgresql stop
        - cp .env.example .env
      install:
        - docker-compose build
      script:
        - sh scripts/lint.sh
        - sh scripts/test.sh
      after_success:
        - sudo mkdir /app
        - sudo cp -r project /app/project
        - pip install coveralls
        - coveralls

    - stage: deploy
      name: "Deploy to QA"
      if: tag IS blank && branch = qa
      before_install: skip
      install: skip
      script: skip
      after_success: echo "Skipping the after_success."  # https://github.com/travis-ci/travis-ci/issues/8337
      deploy:
        provider: script
        script: sh scripts/deploy.sh qa
        on:
          branch: qa

    - name: "Deploy to Production"
      if: tag IS present
      deploy:
        provider: script
        script: sh scripts/deploy.sh production
        on:
          tags: true

notifications:
  email:
    on_success: never
