dist: xenial
language: python
python: 3.7

services:
  - docker

jobs:
  include:
    - stage: lint_and_test
      name: "Lint and Test"
      if: tag IS blank
      before_install:
        - sudo service postgresql stop
        - cp .env.example .env
        # Install Terraform.
        - curl -sLo /tmp/tf.zip https://releases.hashicorp.com/terraform/0.12.8/terraform_0.12.8_linux_amd64.zip
        - unzip /tmp/tf.zip -d ~/bin
        - rm -f /tmp/tf.zip
      install:
        - docker-compose build
      script:
        - sh scripts/lint.sh
        - sh scripts/test.sh
      after_success:
        - sudo mkdir /app
        - sudo cp -r project /app/project
        - pip install coveralls
        - coveralls

    - stage: deploy
      name: "Deploy"
      if: tag IS present
      before_install: skip
      install: skip
      script: skip
      after_success: echo "Skipping the after_success."  # https://github.com/travis-ci/travis-ci/issues/8337
      deploy:
        provider: script
        script: sh scripts/deploy.sh
        on:
          tags: true

notifications:
  email:
    on_success: never
