language: python

python:
  - 3.6

services:
  - docker

before_install:
  - sudo service postgresql stop
  - cp .env.example .env

install:
  - docker-compose up

script:
  - sh scripts/lint.sh
  - sh scripts/test.sh
