dist: xenial

language: python

python: 3.8

services:
  - docker

stages:
  - name: check
    if: |
      tag IS blank && \
      branch != qa

  - name: deploy
    if: |
      tag IS present || \
      branch = qa

jobs:
  include:
    - stage: check
      name: lint
      before_install: skip
      install: docker-compose build
      script: scripts/lint.sh

    - stage: check
      name: test
      before_install:
        - sudo service postgresql stop
        - cp .env.example .env
      install: docker-compose build
      script: scripts/test.sh
      after_success:
        - sudo mkdir /app
        - sudo cp -r project /app/project
        - pip install coveralls
        - coveralls

    - stage: deploy
      name: qa
      if: branch = qa
      before_install: skip
      install: skip
      script: skip
      after_success: true
      deploy:
        provider: script
        script: scripts/deploy.sh qa

    - stage: deploy
      name: production
      if: tag IS present
      before_install: skip
      install: skip
      script: skip
      after_success: true
      deploy:
        provider: script
        script: scripts/deploy.sh production

notifications:
  email:
    on_success: never
