version: '3.7'
services:
  web:
    build:
      context: .
      target: development
    # Run as root user to avoid coverage failing to create .coverage with
    # permission denied in travis.
    user: root
    ports:
      - 8000:8000
    environment:
      WAIT_HOSTS: db:5432
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - db
  db:
    image: postgres:10.7-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: tt
      POSTGRES_USER: tt
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
volumes:
  dbdata:
