version: "3.2"
services:
  web:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    ports:
      - "8000:80"
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      WAIT_HOSTS: db:5432
    depends_on:
      - db
  db:
    image: postgres:10.7-alpine
    environment:
      POSTGRES_DB: tt
      POSTGRES_USER: tt
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
volumes:
  dbdata:
