# Generated by Django 2.2.2 on 2019-06-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("apps_tmdb", "0006_progress_last_check")]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="last_aired_episode",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="last aired episode"
            ),
        ),
        migrations.AddField(
            model_name="progress",
            name="last_aired_season",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="last aired season"
            ),
        ),
    ]
