# Generated by Django 2.2.5 on 2019-10-01 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("apps_tmdb", "0007_auto_20190626_0943")]

    operations = [migrations.RemoveField(model_name="progress", name="last_check")]
