# Generated by Django 3.0.3 on 2020-04-25 11:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_tmdb", "0009_progress_show_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="show_genres",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                default=list,
                size=None,
                verbose_name="show genres",
            ),
        ),
    ]
