# Generated by Django 2.1.7 on 2019-03-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
