# Generated by Django 2.2.5 on 2019-10-01 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("apps_accounts", "0006_user_time_zone")]

    operations = [migrations.RemoveField(model_name="user", name="max_following_shows")]
