# Generated by Django 2.0.7 on 2018-07-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_tmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['-followed', 'next_air_date', 'show_name', 'show_id'], 'verbose_name': 'progress', 'verbose_name_plural': 'progresses'},
        ),
        migrations.AddField(
            model_name='progress',
            name='followed',
            field=models.BooleanField(default=False, verbose_name='followed'),
        ),
    ]
