# Generated by Django 2.1.7 on 2019-03-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_tmdb', '0005_auto_20190309_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last check'),
        ),
    ]
